### ISSUE TITLE
self-play

### ISSUE THREAD

**Issue by dotaking2021** [PettingZoo-Team/PettingZoo#342] opened 2021-03-04 20:11 UTC
Hello

I am interested in formulating Pong to a self-play environment. 

I am following your tutorial here: 

```
from pettingzoo.atari import pong_v0
import supersuit as ss
env = pistonball_v4.parallel_env()
env = ss.color_reduction_v0(env, mode='B')
env = ss.resize_v0(env, x_size=84, y_size=84)
env = ss.frame_stack_v1(env, 3)
env = ss.pettingzoo_env_to_vec_env_v0(env)
env = ss.concat_vec_envs_v0(env, 8, num_cpus=4, base_class='stable_baselines3')
model = PPO('CnnPolicy', env, verbose=3, n_steps=16)
```

If I want to modify this to be self-play, do I need to change `concat_vec_envs_v0 `?

**Comment by weepingwillowben** [comment] 2021-03-04 21:32
Closing as it is a duplicate of https://github.com/PettingZoo-Team/SuperSuit/issues/64

**Closed by weepingwillowben** 2021-03-04 21:32 UTC
