### ISSUE TITLE
TicTacToe environment: understanding game termination and rewards handling

### ISSUE THREAD

**Issue by gsverhoeven** [PettingZoo-Team/PettingZoo#355] opened 2021-03-30 14:07 UTC
Hi there PettingZoo team,

I am implementing independent Q-learning for the TicTicToe environment in PettingZoo.
Thanks for creating this awesome framework.

Currently I am trying to understand how to properly process the termination of a game and the reward bookkeeping for the agents within the AEC model. 

Coming from single-agent Gym, I expect that when the game terminates, the rewards are handed out, both players are done and no agents are available anymore for actions. 

However, in the reproducible example below, after Player 2 has played the winning move, the rewards are indeed handed out (`env.rewards`) and both players are done. Then the iterator moves to Player 1, who collects its reward (-1) through last() and plays action None. Then the iterator moves to Player 2. At this point, Player 1 is removed from the list of current agents and `env.rewards` shows zero reward for Player 2, this is because Player 2 received no reward in the previous turn, which was Player 1's turn? Finally Player 2 collects its reward (+1) using last() and plays action None. Here the difference between env.rewards and the reward from last() becomes visible.

From my understanding so far, I think this is how PettingZoo is designed, can you confirm this?

That leaves for me the puzzle on how to best program game termination and the reward processing :-)
I was using env.rewards and env.dones to break out of the agent iteration prematurely. I now think i should write the code such that the agent iterator loop naturally comes to an end like in the code below.

```
from pettingzoo.classic import tictactoe_v2

env = tictactoe_v2.env()
env.reset()

def policy(observation, agent):
    action = random.choice(np.flatnonzero(observation['action_mask']))
    return action

random.seed(123)

for agent in env.agent_iter():
    print(env.agent_selection)
    print(env.agents)
    print(env.rewards)
    print(env.dones)
    observation, reward, done, info = env.last()
    print(reward)
    action = policy(observation, agent) if not done else None
    env.step(action)
    #env.render()
```

> player_1
> ['player_1', 'player_2']
> {'player_1': 0, 'player_2': 0}
> {'player_1': False, 'player_2': False}
> 0
> player_2
> ['player_1', 'player_2']
> {'player_1': 0, 'player_2': 0}
> {'player_1': False, 'player_2': False}
> 0
> player_1
> ['player_1', 'player_2']
> {'player_1': 0, 'player_2': 0}
> {'player_1': False, 'player_2': False}
> 0
> player_2
> ['player_1', 'player_2']
> {'player_1': 0, 'player_2': 0}
> {'player_1': False, 'player_2': False}
> 0
> player_1
> ['player_1', 'player_2']
> {'player_1': 0, 'player_2': 0}
> {'player_1': False, 'player_2': False}
> 0
> player_2
> ['player_1', 'player_2']
> {'player_1': 0, 'player_2': 0}
> {'player_1': False, 'player_2': False}
> 0
> player_1
> ['player_1', 'player_2']
> {'player_1': 0, 'player_2': 0}
> {'player_1': False, 'player_2': False}
> 0
> player_2
> ['player_1', 'player_2']
> {'player_1': 0, 'player_2': 0}
> {'player_1': False, 'player_2': False}
> 0
> player_1
> ['player_1', 'player_2']
> {'player_1': -1, 'player_2': 1}
> {'player_1': True, 'player_2': True}
> -1
> player_2
> ['player_2']
> {'player_2': 0}
> {'player_2': True}
> 1

**Comment by weepingwillowben** [comment] 2021-03-30 17:11
So all of this is intended behavior. 

The cumulative reward returned by `last()` is designed to accumulate all of the reward that the agent's last action could have produced. In a way it is the delayed reward of your action. Why delay the reward? This is because in RL it is always better to receive a reward late than receive a reward early. Reward late is a credit assignment problem, reward early cannot be learned at all by standard formalisms. PettingZoo is not the only library which does this reward delaying:

[SIMPLE](https://github.com/davidADSP/SIMPLE) does this to: "The wrapper delays the reward back to the PPO agent, until all opponents have taken their turn. "

However, you might not want to process delayed rewards, you might want to process rewards as soon as they are released by the environment. The `.rewards` dictionary is designed to meet this need. It updates every step with the rewards the environment generates that step. So in tictactoe, it updates when the environment terminates, then the environment lets the agents step in the loop in order to collect their cumulative reward with last().

So yes, I think you have the right idea. Unless you are being very careful, early termination is not a good idea.

**Comment by gsverhoeven** [comment] 2021-03-31 21:12
Thank you very much for your prompt reply, good to know that i am on the right track.

I just ran into a new "unexpected behavior" of the tic-tac-toe environment:

I now make use of the `None` action to properly collect the rewards using `last()` .
However, this means that the final state of the game is seen by both Player 1 and Player 2.

I use hashing with defaultdict to create the Q-table while running the algorithm.
Now i was expecting that `hash(str(observation['observation']` would give me a unique key for each board position.

However, when player 1 sees the final state, it is coded as 

```

     |     |     
  O  |  X  |  X  
_____|_____|_____
     |     |     
  O  |  O  |  X  
_____|_____|_____
     |     |     
  X  |  O  |  X  
     |     |     
[[[1 0]
  [1 0]
  [0 1]]

 [[0 1]
  [1 0]
  [1 0]]

 [[0 1]
  [0 1]
  [0 1]]]
```

But when player 2 sees the same final state, the position of 0 and 1 are flipped:
```
     |     |     
  O  |  X  |  X  
_____|_____|_____
     |     |     
  O  |  O  |  X  
_____|_____|_____
     |     |     
  X  |  O  |  X  
     |     |     
[[[0 1]
  [0 1]
  [1 0]]

 [[1 0]
  [0 1]
  [0 1]]

 [[1 0]
  [1 0]
  [1 0]]]
```

The documentation says: 
https://www.pettingzoo.ml/classic/tictactoe

> The main observation is 2 planes of the 3x3 board. The first plane represents the placement of Xs, and the second plane shows the placement of Os. The possible values for each cell are 0 or 1; in the first plane, 1 indicates that an X has been placed in that cell, and 0 indicates that X is not in that cell. Similarly, in the second plane, 1 indicates that an O has been placed in that cell, while 0 indicates that an O has not been placed.

From this description, i would expect that the observation of the final state would be the same, regardless of which player can act.

Could this be a bug?

**Comment by weepingwillowben** [comment] 2021-03-31 22:55
Hi, this is a documentation bug.

The observation is different for each player. 

```
env.observe("player_1")["observation"] != env.observe("player_2")["observation"]
```

The reason they are different is to support a self-play agent that can play both sides of the game.
The observation *must* be different in *every* environment where self-play is viable. Otherwise the agent won't know which player it is playing. We use an observation inspired by AlphaZero so the values in the channels are inverted so that it is symmetric between the players.

**Comment by weepingwillowben** [comment] 2021-03-31 23:04
I tried to address this documentation inadequacy here: #358

**Comment by gsverhoeven** [comment] 2021-04-01 10:19
Thanks for clearing that up, the wording is clear now.

And what about `env.observe()`? According to the documentation this should "return the observation an agent currently can make".
Shouldn't that be inverted as well when I am in a given step in the game cycle?

```
env = tictactoe_v2.env()
env.reset()
env.step(3)
env.observe("player_1")['observation']
```

> array([[[0, 0],
>         [0, 0],
>         [0, 0]],
> 
>        [[0, 1],
>         [0, 0],
>         [0, 0]],
> 
>        [[0, 0],
>         [0, 0],
>         [0, 0]]], dtype=int8)

```
env.observe("player_2")['observation']
```

> array([[[0, 0],
>         [0, 0],
>         [0, 0]],
> 
>        [[0, 1],
>         [0, 0],
>         [0, 0]],
> 
>        [[0, 0],
>         [0, 0],
>         [0, 0]]], dtype=int8)

The observations are equal here.

**Comment by gsverhoeven** [comment] 2021-04-01 12:02
To continue on the theme of unexpected behavior:
```
from pettingzoo.classic import tictactoe_v2

env = tictactoe_v2.env()
env.reset()
env.observe('player_1')
env.observe('player_2')
env.step(0)
```

> [WARNING]: Illegal move made, game terminating with current player losing. 
> obs['action_mask'] contains a mask of all legal moves that can be chosen.

Could calling `observe()` somehow **set** the action_mask that `step()` uses?
I expected `observe()` to be non-interfering with the AEC mechanics.

This works as expected.
```
env = tictactoe_v2.env()
env.reset()
env.observe('player_2')
env.observe('player_1')
env.step(0)
```

**Comment by weepingwillowben** [comment] 2021-04-01 17:47
I'm very sorry you had to find this rather embarrassing bug. 

Indeed the TerminateIllegalWrapper was storing the action mask last produced by observe. 

This is fixed in #359

**Comment by gsverhoeven** [comment] 2021-04-02 14:57
Thanks a lot for the quick fix! I installed PettingZoo from github and in  `tictactoe_v3` above code now runs as expected.

Regarding my question above about `env.observe()` (https://github.com/PettingZoo-Team/PettingZoo/issues/355#issuecomment-811809621) :

```
env = tictactoe_v3.env()
env.reset()
# player 1 acts
env.step(0)
# now player 2 can act:
env.observe('player_1')
env.observe('player_2')
# no channel inversion
```

Here I notice that both calls to `observe()` give me the same observation (no inverting of the channels) for both players, expect the action masks are different (player 2 can act, player 1 cannot). So can we say that conceptually, both players look at the observation as the current ("active" ) player sees it? 

Regards,
Gertjan

**Comment by weepingwillowben** [comment] 2021-04-02 19:07
I'm really sorry, this is another bug. The observations should definitely be different. I saw the bug that caused this issue, but somehow manage to not fix it.

**Comment by weepingwillowben** [comment] 2021-04-02 19:10
This issue (and a similar issue I discovered in connect 4) is now fixed by #362

**Comment by gsverhoeven** [comment] 2021-04-02 20:36
Yes, the channels are inverted now, thanks for fixing this one as well.
All is clear now for me, shall i close the issue? Am not sure what the etiquette is here :-)

Regards
Gertjan

**Comment by justinkterry** [comment] 2021-04-02 21:14
I can close it :)


If for some reason you happen to have a desire to do QA for other classic environments (or are trying to avoid it again), checkers and backgammon are definitely the most likely to have bugs. The logic for them came from external codebases that was never super extensively used before integration into PettingZoo, and I don't believe they're super popular with our users (which is how these problems in tictactoe and connect four persisted for a year).

**Closed** 2021-04-02 21:27 UTC
